import {
  lucideBaby,
  lucideBanknote,
  lucideBriefcase,
  lucideBus,
  lucideCar,
  lucideClapperboard,
  lucideCoffee,
  lucideCreditCard,
  lucideDumbbell,
  lucideFuel,
  lucideGift,
  lucideGraduationCap,
  lucideHandCoins,
  lucideHeartPulse,
  lucideHome,
  lucideLandmark,
  lucidePawPrint,
  lucidePiggyBank,
  lucidePlane,
  lucideReceipt,
  lucideShield,
  lucideShirt,
  lucideShoppingBag,
  lucideShoppingCart,
  lucideSmartphone,
  lucideSofa,
  lucideSparkles,
  lucideTag,
  lucideTrendingUp,
  lucideUsers,
  lucideUtensils,
  lucideWifi,
  lucideWrench,
} from '@ng-icons/lucide';

/** Icone lucide proposte per le categorie, adatte a voci di spesa/entrata comuni. */
export const CATEGORY_ICONS = {
  lucideUtensils,
  lucideShoppingCart,
  lucideShoppingBag,
  lucideCoffee,
  lucideCar,
  lucideFuel,
  lucideBus,
  lucideHome,
  lucideWifi,
  lucideSmartphone,
  lucideHeartPulse,
  lucideShirt,
  lucideClapperboard,
  lucideGraduationCap,
  lucideBriefcase,
  lucideGift,
  lucidePlane,
  lucidePawPrint,
  lucideShield,
  lucidePiggyBank,
  lucideDumbbell,
  lucideSparkles,
  lucideLandmark,
  lucideWrench,
  lucideSofa,
  lucideHandCoins,
  lucideBaby,
  lucideCreditCard,
  lucideBanknote,
  lucideTrendingUp,
  lucideReceipt,
  lucideUsers,
  lucideTag,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);
